#getprop ro.product.name | grep daisy || abort "only daisy suported"
ui_print "-------------------------------------------------------"
ui_print "Developer: @Ket"
ui_print "Joind my channel for updates: t.me/caticerstuff"
#ui_print "Warning! Beta versions may cause some bugs!"
ui_print "-------------------------------------------------------"
ui_print "- For Android 8.1,9,10,11 Roms & GSI's"
ui_print "- Verison: V4-Release"
ui_print "-------------------------------------------------------"
ui_print "Changelog:"
ui_print "-------------------------------------------------------"
ui_print "4-Beta:"
ui_print "- Fixed Manual shutter speed option"
ui_print "-------------------------------------------------------"
