# getprop ro.product.name | grep daisy || abort "only daisy suported"
ui_print "  @Caticer"
ui_print "- Warning! Beta version may cause some bugs!"
ui_print "- For Android 8.1/9/10/11 Roms and GSI's"
ui_print "- V2 version"
ui_print "- 32s manuel Shutter speed"
ui_print "- 4K video"
ui_print "- And more+"
