# getprop ro.product.name | grep daisy || abort "only daisy suported"
ui_print "-------------------------------------------------------"
ui_print "Developer: @Caticer"
ui_print "Joind my channel for updates: t.me/caticerstuff"
ui_print "Warning! Beta versions may cause some bugs!"
ui_print "-------------------------------------------------------"
ui_print "- For Android 8.1/9/10/11 Roms and GSI's"
ui_print "- Verison: V3-Beta"
ui_print "-------------------------------------------------------"
ui_print "Changelog:"
ui_print "- Fixed random crash"
ui_print "- New App icon"
ui_print "- Full Hal3 complatible"
ui_print "- Fixed no portraid and HDR pro option whith pixel props"
ui_print "- Added more bugs to fix later"
